In [ ]:
import numpy as np

In [ ]:
def obe(matriks, hasil):
  for i in range(len(matriks)):
    if matriks[i][i] == 0:
      c = 0
      for j in range(i + 1, len(matriks)):
        if matriks[j][i] != 0:
          matriks[i], matriks[j] = matriks[j].copy(), matriks[i].copy()
          hasil[i], hasil[j] = hasil[j].copy(), hasil[i].copy()
          c = 1
          break
      if c == 0:
        hasil = "Matriks tidak memiliki solusi cik😋"
        return matriks, hasil
    a = matriks[i][i]
    matriks[i][i] = matriks[i][i] * (1/a)
    hasil[i] = hasil[i] * (1/ a)
    for j in range(len(matriks[i])):
      if i != j:
        matriks[i][j] /= a
    for k in range(len(matriks)):
      if i != k:
        pembuatNol = matriks[k][i]
        for l in range(len(matriks[k])):
          matriks[k][l] -= pembuatNol * matriks[i][l]
        hasil[k] -= pembuatNol * hasil[i]
  return matriks, hasil

##Soal No 1

In [ ]:
matriks = np.array([[4, -3, 1], [2, 1, -4], [1, 2, -2]]).astype(float)
hasil = np.array([11, -1, 1]).astype(float)

matriks, hasil = obe(matriks, hasil)
print(f"matriks: \n{matriks}")
print(f"hasil: \n{hasil}")

matriks: 
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
hasil: 
[3. 1. 2.]


##Soal No 2

In [ ]:
matriks = np.array([[1, -1, 1,-2], [2, -1, 2, -1], [-1, 1, 2, -1],[1,2,4,1]]).astype(float)
hasil = np.array([8, 5, 4, 5]).astype(float)
matriks, hasil = obe(matriks, hasil)
print(f"matriks: \n{matriks}")
print(f"hasil: \n{hasil}")

matriks: 
[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [-0. -0. -0.  1.]]
hasil: 
[ 5.  7. -2. -6.]


##Soal No 3

In [ ]:
matriks = np.array([[1, 3, 6], [2, 8, 16], [5, 21, 45]]).astype(float)
hasil = np.array([17, 42, 91]).astype(float)
matriks, hasil = obe(matriks, hasil)
print(f"matriks: \n{matriks}")
print(f"hasil: \n{hasil}")

matriks: 
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
hasil: 
[ 5. 16. -6.]
